### ISSUE TITLE
symfony 6 problem ?

### ISSUE THREAD

**Issue by stloc** [Tom32i/content#153]
`php bin/console -e prod stenope:build ./static`

`{"message":"Error thrown while running command \"-e prod 'stenope:build' './static'\". Message: \"There are no commands defined in the \"stenope\" namespace.\"","context":{"exception":{"class":"Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException","message":"There are no commands defined in the \"stenope\" namespace.","code":0,"file":"/home/lapp/dev/test/vendor/symfony/console/Application.php:622"},"command":"-e prod 'stenope:build' './static'","message":"There are no commands defined in the \"stenope\" namespace."},"level":500,"level_name":"CRITICAL","channel":"console","datetime":"2022-10-05T16:34:38.722606+02:00","extra":{}}`

**Comment by stloc** [comment]
Resolved ! I have clear my prod cache and restart the command. Good

**Comment by ogizanagi** [comment]
Nice 👌🏻 Indeed, prod env does not detect changes automatically, so you need to clear the cache beforehand.

> **Note**: The stenope is not meant to be called in dev mode, so don't worry about the `_profiler/**` pages as shown in your screen.

Generate your static build using:

```shell
APP_ENV=prod bin/console cache:clear
APP_ENV=prod bin/console stenope:build ./static
```
